name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: '5.7' # Optional, default value is "latest". The version of the MySQL
        mysql root password: 666666
    - uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: '4.2.0' # Optional, default value is "latest". The version of the MongoDB
    - name: check
      run: ./gradlew check -PdatabasePassword=666666
